# Generated by Django 2.2.3 on 2019-07-30 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190729_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Favorite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
