# Generated by Django 2.2.3 on 2019-08-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
