# Generated by Django 2.2.3 on 2019-08-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190801_1429'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table=None,
        ),
    ]
