# Generated by Django 2.2.3 on 2019-08-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190806_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='category',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
